{-
   api
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 1.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Default exposing
    ( getHoges
    , postFoos
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



getHoges : Maybe String -> Api.Request (List Api.Data.Hoge)
getHoges authorization_header =
    Api.request
        "GET"
        "/hoges"
        []
        []
        [ ( "Authorization", Maybe.map identity authorization_header ) ]
        Nothing
        (Json.Decode.list Api.Data.hogeDecoder)



postFoos : Maybe String -> Maybe Api.Data.Foo -> Api.Request ()
postFoos authorization_header foo_body =
    Api.request
        "POST"
        "/foos"
        []
        []
        [ ( "Authorization", Maybe.map identity authorization_header ) ]
        (Maybe.map Api.Data.encodeFoo foo_body)
        (Json.Decode.succeed ())
